### ISSUE TITLE
Indentation of function arguments

### ISSUE THREAD

**Issue by vincentbernat** [lunaryorn/puppet-mode#60]
Hey!

Something like this is not correctly indented:

```puppet
class something(
  $param1 = 3,
  $param4 = 5
) {
  $stuff = 18
}
```

I get:

```puppet
class something(
  $param1 = 3,
  $param4 = 5
  ) {
  $stuff = 18
}
```

And if I force the closing parenthesis to be at the beginning of the line, I get:

```puppet
class something(
  $param1 = 3,
  $param4 = 5
) {
$stuff = 18
}
```

(`$stuff` not indented properly).

**Comment by runejuhl** [comment]
Seems like we end at `https://github.com/lunaryorn/puppet-mode/blob/master/puppet-mode.el#L625` when running `puppet-indent-line` on that particular line. At that point `(forwardline -1)` has been called until the cursor is at the first line (`class ....`). Since that line ends with an opening parenthesis, we indent with indentation of `puppet-indentat-level`.

Would it be sufficient to check if the line of the opening parenthesis starts with `class`, and if true, set the indent level to that of the line?
